## Assessment overview

This course will be assessed on the basis of a **3 formative assessments** and **2 summative assessments**.

**Formative assessments** are assessments that you can receive feedback on, but which will not be marked. These will give you a chance to keep on track with the course contents and get interim feedback that will better prepare you for the summative assessment. See below for info.

You will have to submit **two summative assessments**. They will weight 40% and 60% of the final mark.

See below for details.

## Formative assessments

::: {.callout-warning collapse="true" icon="false"}
## Formative 1: Week 5 (Due Thursday 16 February at NOON)

**Data summary and visualisation**

- Formative assessment 1 requires you to read, mutate and plot a given data set. You can preview the formative instructions here: <https://github.com/uoelel/sqmb-f1>.

- We will use GitHub Classroom for all assessments. For an overview of how GitHub Classroom works, watch [these videos](https://youtube.com/playlist?list=PLiqxyEAY_i3kItjlvEYN1VCwHvAdP6hZW).

- The GitHub Classroom invitation link can be found on Learn.
:::

::: {.callout-warning collapse="true" icon="false"}
## Formative 2: Week 6 (Due Thursday 2 March at NOON)

**Statistical modelling**

- F2 requires you to find a data table and fit a model with one continuous outcome and one categorical predictor. You can preview the instructions here: <https://github.com/uoelel/sqmb-f2>.

- From the .Rmd file, you will render a PDF and submit it over Turnitin. You can find the link to Turnitin on Learn under Assessment \> Formative Assessment F2.

:::

::: {.callout-warning collapse="false" icon="false"}
## Formative 3: Week 11 (Due Thursday 6 April at NOON)

**Data analysis report**

- Given a data table and a research question, submit a short and concise data analysis report, including summary measures, plots, and a linear model. You can download everything you need from here: <https://github.com/uoelel/sqmb-f3>.

- From the .Rmd file, you will render a PDF and submit it over Turnitin. You can find the link to Turnitin on Learn under Assessment \> Formative Assessment F3.

:::

## Summative assessments

::: {.callout-important collapse="false" icon="false"}
## Summative 1 - Thu 30 March

**Due on Thursday 30 March at noon**

The first summative contains a series of guided exercises. 
You can find the summative materials and exercises here: <https://github.com/uoelel/sqmb-s1>.
:::

::: {.callout-important collapse="true" icon="false"}
## Summative 2 - Thu 27 April

**Due on Thursday 27 April at noon**

The second summative will be in the form of a data analysis report. 
We will provide a number of data sets paired with hypotheses.
You will choose one data set/hypothesis pair and, with it, conduct the full workflow of a Bayesian data analysis.

You can find the list of data sets here: TBA.
:::
