---
title: "Statistics and Quantitative Methods (Semester 2)"
---

Welcome to the main site of the course *Statistics and Quantitative Methods* (Semester 2).

This will be your go-to place throughout the semester.

This course is an introduction to study design, statistics and quantitative data analysis as commonly employed in linguistics, using the R software.

## Course description

The course will cover the basics of **statistics and quantitative data analysis**, and how to **design studies** that effectively address the intended research questions. Students will learn the principles of **data visualisation and statistical modelling** and develop the practical skills necessary to perform such analyses. The course will draw examples from different branches of linguistics and will provide students with hands-on experience in open science practices.

The course will teach students how to carry out Bayesian statistical inference using a variety of statistical models, and how to interpret results from traditional Null Hypothesis Significance Testing (i.e. *p*-values and confidence intervals).

## R and RStudio

The workshops will be held in the PPLS Computer Lab. The Lab is equipped with PCs running Windows and Ubuntu. The Lab PCs will have all the necessary software.

**You can choose to use your own laptop instead of the Lab PCs.**

This requires you to have **both R and RStudio** installed on your laptop.

::: {.callout-tip icon="false"}
## Installation instructions

**NOTE**: If you have installed either R or RStudio prior to January 2023, please delete both R and RStudio from your laptop and reinstall them.

To (re)install R and RStudio, follow the instructions for **Step 1 and 2** here: <https://posit.co/download/rstudio-desktop/>.
:::
