## Overview

This course is an introduction to **quantitative data analysis**, as commonly employed in linguistics, using the R software.

We will cover the following **topics**:

-   The basics of quantitative data analysis.
-   Data preparation.
-   Data summaries.
-   Principles of **data visualisation**.
-   Statistical modelling with **linear models**.
-   Statistical inference using **Bayesian inference**.

At completion of the course you will have gained the following **skills**:

-   Import common data formats, tidy and transform data.
-   Choosing and reporting appropriate summary measures.
-   Using compelling visualisations to communicate a specific message about patterns in the data.
-   Master linear models for different types of data (continuous measures and binary outcomes).
-   Using Bayesian inference to answer research questions and avoid common interpretation pitfalls.

Examples from different branches of linguistics will be used to provide you with hands-on experience in quantitative data analysis and Open Research practices.

## Weekly plan

### Week 1: Quantitative methods and uncertainty

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

-   What is quantitative data analysis?
-   What is the inference process?
-   How can we talk about uncertainty and variability?
-   Which are the limits of quantitative methods?

**Skills**

-   Think critically about statistics, uncertainty and variability.
-   Use R to perform simple calculations.
-   Master the basics of the programming language R.
-   Use RStudio.
:::

::: {.callout-note collapse="true"}
#### Homework

**Intake form**

- **You must complete the intake form before coming to the Tuesday lecture.**
- The link to the form will be circulated via Learn.

**Install R and RStudio**

- If you with to use your own laptop for the workshops, instead of the Lab PCs, you need to install both R and RStudio.
- **NOTE**: If you have installed either R or RStudio prior to January 2023, please make sure you delete both R and RStudio from your laptop.
- Please, follow the instructions for **Step 1 and 2** here: <https://posit.co/download/rstudio-desktop/>.

:::

::: {.callout-tip collapse="true"}
#### Materials

- [Lecture slides](slides/w01/).
- [Workshop tutorial](tutorials/tutorial-w01.qmd).
:::

::: {.callout-tip collapse="true"}
#### Suggested readings

**Main textbooks**

- Statistics for Linguists with R, by Bodo Winter (**S4LR**) Ch. 1. [via library]
- R for Data Science (**R4DS**) [Ch. 1](https://r4ds.had.co.nz/introduction.html), [Ch. 2](https://r4ds.had.co.nz/explore-intro.html). [online book]
- Statistical (Re)thinking, by Richard McElreath (**SReT**), Ch. 1. [via library]

**Papers**

- [Darwin Holmes 2020](https://doi.org/10.34293/education.v8i4.3232). Researcher Positionality - A Consideration of Its Influence and Place in Qualitative Research - A New Researcher Guide
- [Jafar 2018](https://doi.org/10.1136/emermed-2017-207158). What is positionality and should it be expressed in quantitative studies?

**From the lecture**

- [Silberzahn et al. 2018](https://doi.org/10.1177/2515245917747646
). Many Analysts, One Data Set: Making Transparent How Variations in Analytic Choices Affect Results
- [Coretta et al. (in principle)](https://doi.org/10.31234/osf.io/q8t2k). Multidimensional signals and analytic flexibility: Estimating degrees of freedom in human speech analyses
- [Cumming 2014](https://doi.org/10.1177%2F0956797613504966). The New Statistics: Why and How
- [Kurschke and Liddell 2018](https://doi.org/10.3758/s13423-016-1221-4). The Bayesian New Statistics: Hypothesis testing, estimation, meta-analysis, and power analysis from a Bayesian perspective
:::

### Week 2: Data wrangling

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

- What are the types of statistical variables?
- Which summary measures are appropriate for which types of variables?
- What are common measures central tendency?
- What are common measures of dispersion?

**Skills**

-   Organise files efficiently.
-   Import tabular data in R.
-   Obtain mean, median, mode, range and standard deviation.
-   Use R scripts to save and reuse code.
:::

::: {.callout-tip collapse="true"}
#### Materials

- [Lecture slides](slides/w02/).
- [Workshop tutorial](tutorials/tutorial-w02.qmd).
- Workshop files (right-click and download):
  - [shallow.csv](data/shallow.csv)
:::

::: {.callout-tip collapse="false"}
#### Suggested readings

**Main textbooks**

- **S4LR** Ch. 3. [via library]
- **R4DS** [Ch. 4](https://r4ds.had.co.nz/workflow-basics.html) and [Ch. 5](https://r4ds.had.co.nz/transform.html). [online book]
:::

### Week 3: Data visualisation

::: {.callout-important collapse="false"}
#### Learning Objectives

**Questions**

- What are the principles of good data visualisation?
- Which are the main components of a plot?
- Which are the appropriate plots for different types of data?
- How can we visualise uncertainty?


**Skills**

- Create common types of plots with ggplot2.
- Use colour and shape to effectively convey meaning.
- Describe a plot in writing and comment on observable patterns.
- Filter and mutate data.
:::

::: {.callout-tip collapse="false"}
#### Materials

- [Lecture slides](slides/w03/).
<!-- - [Workshop tutorial](tutorials/tutorial-w02.qmd). -->
<!-- - Workshop files (right-click and download): -->
<!--   - [shallow.csv](data/shallow.csv) -->
:::

### Week 4: Linear models, Basics I

::: {.callout-warning collapse="false"}
#### Formative assessment 1

- Formative assessment 1 requires you to read, mutate and plot a given data set. You can preview the formative instructions here: <https://github.com/uoeling/sqmb-f1>.

- We will use GitHub Classroom for all assessments. For an overview of how GitHub Classroom works, watch [these videos](https://youtube.com/playlist?list=PLiqxyEAY_i3kItjlvEYN1VCwHvAdP6hZW).

- GitHub Classroom invitation links will be circulated via Learn.

:::

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

- What are statistical models useful for?
- What are statistical populations, samples and distributions?
- What are statistical variables and which type of relationships exist between variables?
- What is a linear model and which are its components?


**Skills**

- Fit a linear model with one continuous outcome variable and one continuous predictor with `brm()`.
- Interpret the summary of the model and understand the meaning of the reported coefficients.
- Plot and diagnose linear models.
- Describe the model specification and results in writing.
:::


### Week 5: Linear models, Basics II

::: {.callout-important collapse="true"}
#### Learning Objectives

**Questions**

- How can we use linear models with categorical (rather than continuous) predictors?
- Why do we need to code categorical predictors as numbers? And which are the most common coding methods?
- How can we represent a linear model using a formula?
- How do you interpret a linear model with both continuous and categorical predictors?


**Skills**

- Master contrast coding in R for categorical predictors.
- Fit, interpret and plot linear models with continuous and categorical predictors.
- Understand treatment and sum coding.
- Advanced reporting of model specification and results.
:::
